### ISSUE TITLE
Near Cache

### ISSUE THREAD

**Issue by mslinn** [nilskp/hazelcast-scala#2]
I have been playing with near cache code, originally written in Java, that I [adapted for Scala](https://github.com/mslinn/NearTest/tree/master/src/main/scala). 

I see [you have](https://github.com/nilskp/hazelcast-scala/blob/master/src/main/scala/com/hazelcast/Scala/map-events.scala) `MapListener` and `EntryListener` case classes, and I see the MapListener is used in [onMapEvents](https://github.com/nilskp/hazelcast-scala/blob/master/src/main/scala/com/hazelcast/Scala/HzMap.scala#L137-L145). 

How can I use `onMapEvents` to keep a near cache in sync with the server? BTW, [my code](https://github.com/mslinn/NearTest/issues/1) doesn't quite work, not sure why.

**Comment by nilskp** [comment]
The Hazelcast near-cache is handled transparently, no need for you to do anything other than configure it. 
Also, the `LocalMapStats` are for members, not clients, which is why the hits are 0.

If you explicitly want to listen to map updates, you can do something like this:
```scala
cityProxy.onKeyEvents() {
  case KeyAdded(key) => println(s"Key added: $key")
  case KeyUpdated(key) => println(s"Key updated: $key")
}
```

**Comment by mslinn** [comment]
That worked nicely!
