### ISSUE TITLE
import com.hazelcast.config._ fails

### ISSUE THREAD

**Issue by mslinn** [nilskp/hazelcast-scala#4]
The above import mentioned in README.md fails. Perhaps this project's dependencies need to be augmented to include the Java Hazelcast library?

**Comment by nilskp** [comment]
I'm generally not a fan of making hard dependencies, so both Scala and Hazelcast are defined as `provided` dependencies, meaning you must include them specifically. This is both to avoid versioning conflicts, but also because e.g. Hazelcast has both an open-source and an enterprise version.

**Comment by mslinn** [comment]
Fair enough, this belongs in the readme
